language: rust
dist: bionic

# request macOS 10.15.7
matrix:
  include:
  - os: linux
    rust: stable
  - os: osx
    osx_image: xcode12.2
    rust: stable

branches:
  only:
    - "master"

addons:
  apt:
    packages:
      - libzmq3-dev
      - libgtk-3-dev
      - libcurl4-openssl-dev
      - libssl-dev
  homebrew:
    update: true # if not then pango lib for gtk3 won't build
    packages:
      - zmq
      - gtk+3
      - cairo

script:
  - make

notifications:
  email:
  - andrew@mackenzie-serres.net